apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name:  prestashop-data-php
  namespace: project-ps-dev
  labels:
    app: ps-dev
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd #pd-standard
  fstype: ext4
  replication-type: none
